### ISSUE TITLE
Way to add a flight without the UI.

### ISSUE THREAD

**Issue by drinchev** [appintheair/aita-track-flight-scheme#2]
Hello,

I'm trying to add a past flight to the app via the URI ( create a proper link and open it on my Phone ), but it seems that nothing happens.

Is there a way to use the URI from let's say a copy & pasted link on my phone?

Thanks,

P.S. Awesome app btw.

**Comment by wannabehero** [comment]
Ivan, can you please post sample URL that you use?
Note, that you should have `source` param whitelisted by us.

Send your integration description to support@appintheair.mobi and we'll be
glad to whitelist your app.

**Comment by drinchev** [comment]
The problem is that I don't have an app at all.

I thought you could add flights from a link that is let's say in a website, not in an app.

Anyway I will close the issue and will send you an e-mail these days.

Kudos for the app!
